// lib/react/title.js
/**
 * Created by WangCK on 2016/11/18.
 */
var React = require('react');
var weui = require('../../assets/weui/weui.css');

var Title = React.createClass({
	render: function () {
		return (
			<div className={weui.hd}>
				<h1 className={weui.page_title}>MiniSite</h1>
			</div>
		);
	}
});

module.exports = Title;

// lib/vue/Title.vue
<template>
    <div v-bind:class="css.hd">
        <h1 v-bind:class="css.page_title">MiniSite</h1>
    </div>
</template>

<script>
    import weui from '../../assets/weui/weui.css';

    export default {
        name: 'head',
        data () {
            return {
                css: weui
            }
        }
    }
</script>
