// app/react/controller.js
/**
 * Created by WangCK on 2016/11/18.
 */
var React = require('react');
var jQuery = require('jQuery');
var LoadingAnimation = require('./loading.js');
var Title = require('./title.js');
var Site = require('./site.js');
var Bottom = require('./bottom.js');

var MiniSite = React.createClass({
	getInitialState: function () {
		return {
			site: [],
			selected: [],
			select: [],
			loading: true
		};
	},
	componentWillMount: function () {
		this.getData('http://mini.com/getSite', null, null, function (response) {
			this.setState({
				site: response,
				loading: false
			});
		}.bind(this));
	},
	componentDidMount: function () {
		this.checkSelected();
		setInterval(function () {
			this.checkSelected();
		}.bind(this), 5000);
	},
	getData: function (url, data, method, callback) {
		jQuery.ajax({
			type: method || 'GET',
			url: url,
			data: data || {},
			dataType: 'json',
			success: function (response) {
				callback && callback(response);
			},
			error: function (error) {}
		});
	},
	checkSelected: function () {
		this.getData('http://mini.com/checkSelected', null, null, function (response) {
			var site = this.state.site;
			for (var i = 0; i < response.length; i++) {
				site[response[i].id - 1].selected = 1;
			}
			this.setState({
				site: site
			});
		}.bind(this));
	},
	selectSite: function (el, index) {
		if (el.selected === 1) {
			return false;
		}
		var select = this.state.select, site = this.state.site;
		select.push({id: el.id, siteIndex: index});
		site[index].selected = 1;
		this.setState({
			select: select,
			site: site
		});
	},
	close: function (index, siteIndex) {
		var select = this.state.select, site = this.state.site;
		select.splice(index, 1);
		site[siteIndex].selected = 0;
		this.setState({
			select: select,
			site: site
		});
	},
	submit: function () {
		if (this.state.select.length < 1 || this.state.loading) {
			return false;
		}
		this.setState({
			loading: true
		});
		var data = {id: ''};
		for (var i in this.state.select) {
			data.id += this.state.select[i].id + ',';
		}
		this.getData('http://mini.com/insertSite', data, 'POST', function (response) {
			if (response === 1) {
				var site = this.state.site;
				for (var i in this.state.select) {
					site[this.state.select[i].siteIndex].selected = 1;
				}
				this.setState({
					site: site,
					loading: false,
					select: []
				});
				alert('选座成功');
			} else {
				alert('选座失败');
			}
		}.bind(this))
	},
	render: function () {
		return (
			<div>
				<Title />
				<Site selectSite={this.selectSite} site={this.state.site} />
				<Bottom submit={this.submit} close={this.close} select={this.state.select} />
				<LoadingAnimation display={this.state.loading} />
			</div>
		);
	}
});

module.exports = MiniSite;

// app/vue/Controller.vue
<template>
    <div id="controller">
        <Titles></Titles>
        <Site v-bind:site="site" v-on:select="selectSite"></Site>
        <Selected v-on:close="close" v-on:submit="submit" v-bind:select="select"></Selected>
        <Loading v-bind:loading="loading"></Loading>
    </div>
</template>

<script>
    import jQuery from 'jQuery';
    import Titles from './Title';
    import Loading from './Loading';
    import Site from './Site';
    import Selected from './Selected';

    export default {
        name: 'controller',
        data () {
            return {
                loading: true,
                site: [],
                select: [],
                selected: []
            }
        },
        components: {
            Titles,
            Loading,
            Site,
            Selected
        },
        created () {
            this.getData('http://mini.com/getSite', null, null, function (response) {
                this.site = response;
                this.checkSelected(function () {
                    this.loading = false;
                }.bind(this));
                setInterval(function () {
                    this.checkSelected();
                }.bind(this), 5000);
            }.bind(this));
        },
        methods: {
            getData (url, data, method, callback) {
                jQuery.ajax({
                    type: method || 'GET',
                    url: url,
                    data: data || {},
                    dataType: 'json',
                    success: function (response) {
                        callback && callback(response);
                    },
                    error: function (error) {}
                });
            },
            checkSelected (callback) {
                this.getData('http://mini.com/checkSelected', null, null, function (response) {
                    this.selected = response;
                    for (var i = 0; i < this.selected.length; i++) {
                        this.site[this.selected[i].id - 1].selected = 1;
                    }
                    callback && callback();
                }.bind(this));
            },
            selectSite (el, index) {
                if (el.selected === 1) {
                    return false;
                }
                this.select.push({id: el.id, siteIndex: index});
                this.site[index].selected = 1;
            },
            close (index, siteIndex) {
                this.select.splice(index, 1);
		        this.site[siteIndex].selected = 0;
            },
            submit () {
                if (this.select.length < 1 || this.loading) {
                    return false;
                }
                this.loading = true;
                var i, data = '';
                for (i in this.select) {
                    data += this.select[i].id + ',';
                }
                this.getData('http://mini.com/insertSite', {id: data}, 'POST', function (response) {
                    if (response === 1) {
                        for (i in this.select) {
                            this.site[this.select[i].siteIndex].selected = 1;
                        }
                        this.select = [];
                        this.loading = false;
                        alert('选座成功');
                    } else {
                        alert('选座失败');
                    }
                }.bind(this))
            }
        }
    }
</script>
