// lib/vue/Loading.vue
<template>
    <div class="loading" v-show="loading">
        <div class="spinner">
            <div class="spinner-container container1">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container2">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
            <div class="spinner-container container3">
                <div class="circle1"></div>
                <div class="circle2"></div>
                <div class="circle3"></div>
                <div class="circle4"></div>
            </div>
        </div>
    </div>
</template>

<script>
    export default {
        name: 'loading',
        props: ['loading']
    }
</script>

// app/react/loading.js
/**
 * Created by WangCK on 2016/11/18.
 */
var React = require('react');

var LoadingAnimation = React.createClass({
	render: function () {
		var display = this.props.display ? 'block' : 'none';
		return (
			<div className="loading" style={{display: display}}>
				<div className="spinner">
					<div className="spinner-container container1">
						<div className="circle1"></div>
						<div className="circle2"></div>
						<div className="circle3"></div>
						<div className="circle4"></div>
					</div>
					<div className="spinner-container container2">
						<div className="circle1"></div>
						<div className="circle2"></div>
						<div className="circle3"></div>
						<div className="circle4"></div>
					</div>
					<div className="spinner-container container3">
						<div className="circle1"></div>
						<div className="circle2"></div>
						<div className="circle3"></div>
						<div className="circle4"></div>
					</div>
				</div>
			</div>
		);
	}
});

module.exports = LoadingAnimation;
