// lib/vue/Site.vue
<template>
    <div v-bind:class="weui.bd">
        <div v-bind:class="css.site">
            <div v-for="(el, index) in site" track-by="$index" v-bind:class="css.site_icon + ' ' + (el.selected ? css.site_icon_selected : '')" v-on:click="selectSite(el, index)">{{ el.id }}</div>
        </div>
    </div>
</template>

<script>
    import weui from '../../assets/weui/weui.css';
    import css from '../../assets/weui/custom.css';

    export default {
        name: 'Site',
        props: ['site'],
        data () {
            return {
                css: css,
                weui: weui,
            }
        },
        methods: {
            selectSite (el, index) {
                this.$emit('select', el, index);
            }
        }
    }
</script>

// lib/react/Flux/MiniSite/Components/Site.jsx
/**
 * Created by WangCK on 2016/12/11.
 */
import React from 'react';
import weui from 'weui/weui.css';
import css from 'weui/custom.css';

class Site extends React.Component {
	constructor () {
		super();
		this.selectSite = this.selectSite.bind(this);
	}

	selectSite (el, index) {
		this.props.selectSite(el, index);
	}

	render() {
		let site = this.props.site;
		let siteElement = site.map((el, index) => {
			let className = el.selected ? css.site_icon + ' ' + css.site_icon_selected : css.site_icon;
			return (
				<div className={className} onClick={this.selectSite(el, index)} key={index} value={el.selected}>{el.id}</div>
			);
		})

		return (
			<div className={weui.bd + ' ' + weui.spacing}>
				<div className={css.site}>
					{siteElement}
				</div>
			</div>
		);
	}
}

export default Site;
