// lib/vue/Site.vue
<template>
    <div v-bind:class="weui.bd">
        <div v-bind:class="css.site">
            <div v-for="(el, index) in site" track-by="$index" v-bind:class="css.site_icon + ' ' + (el.selected ? css.site_icon_selected : '')" v-on:click="selectSite(el, index)">{{ el.id }}</div>
        </div>
    </div>
</template>

<script>
    import weui from '../../assets/weui/weui.css';
    import css from '../../assets/weui/custom.css';

    export default {
        name: 'Site',
        props: ['site'],
        data () {
            return {
                css: css,
                weui: weui,
            }
        },
        methods: {
            selectSite (el, index) {
                this.$emit('select', el, index);
            }
        }
    }
</script>

// lib/react/site.js
/**
 * Created by WangCK on 2016/11/18.
 */
var React = require('react');
var weui = require('../../assets/weui/weui.css');
var css = require('../../assets/weui/custom.css');

var Site = React.createClass({
	selectSite: function (el, index) {
		this.props.selectSite(el, index);
	},
	render: function () {
		var site = this.props.site;
		var siteElement = site.map(function (el, index) {
			var className = el.selected ? css.site_icon + ' ' + css.site_icon_selected : css.site_icon;
			return (
				<div className={className} onClick={this.selectSite.bind(this, el, index)} key={index} value={el.selected}>{el.id}</div>
			);
		}.bind(this))
		return (
			<div className={weui.bd + ' ' + weui.spacing}>
				<div className={css.site}>
					{siteElement}
				</div>
			</div>
		);
	}
});

module.exports = Site;
