// lib/vue/Controller.vue
<template>
    <div id="controller">
        <Titles></Titles>
        <Site v-bind:site="site" v-on:select="selectSite"></Site>
        <Selected v-on:close="close" v-on:submit="submit" v-bind:select="select"></Selected>
        <Loading v-bind:loading="loading"></Loading>
    </div>
</template>

<script>
    import jQuery from 'jQuery';
    import Titles from './Title';
    import Loading from './Loading';
    import Site from './Site';
    import Selected from './Selected';
    import Q from 'q';

    export default {
        name: 'controller',
        data () {
            return {
                loading: true,
                site: [],
                select: []
            }
        },
        components: {
            Titles,
            Loading,
            Site,
            Selected
        },
        created () {
            this.getData('getSite').then(response => {
                this.site = response;
                this.checkSelected(() => this.loading = false);
            });
        },
        mounted () {
            setInterval(() => this.checkSelected(), 5000);
            console.log('vue');
        },
        methods: {
            getData (url, data) {
                let deferred = Q.defer();
                jQuery.ajax({
                    type: data ? 'POST' : 'GET',
                    url: 'http://mini.com/' + url,
                    data: data || {},
                    dataType: 'json',
                    success: deferred.resolve,
                    error: deferred.reject
                });
                return deferred.promise;
            },
            checkSelected (callback) {
                this.getData('checkSelected').then(response => {
                    for (let i = 0; i < response.length; i++) {
                        this.site[response[i].id - 1].selected = 1;
                    }
                    callback && callback();
                });
            },
            selectSite (el, index) {
                if (el.selected === 1) {
                    return false;
                }
                this.select.push({
                    id: el.id,
                    siteIndex: index
                });
                this.site[index].selected = 1;
            },
            close (index, siteIndex) {
                this.select.splice(index, 1);
		        this.site[siteIndex].selected = 0;
            },
            submit () {
                if (this.select.length < 1 || this.loading) {
                    return false;
                }
                this.loading = true;
                let i, data = '';
                for (i in this.select) {
                    data += this.select[i].id + ',';
                }
                this.getData('insertSite', {id: data}).then(response => {
                    if (response === 1) {
                        for (i in this.select) {
                            this.site[this.select[i].siteIndex].selected = 1;
                        }
                        this.select = [];
                        this.loading = false;
                    } else {
                        window.alert('选座失败');
                        return;
                    }
                });
            }
        }
    }
</script>

// lib/react/Flux/MiniSite/Controller.jsx
/**
 * Created by WangCK on 2016/12/11.
 */
import React from 'react';
import Store from './Store';
import Actions from './Actions';
import Title from './Components/Title'
import Loading from './Components/Loading'
import Site from './Components/Site'
import Bottom from './Components/Bottom'

class Controller extends React.Component {
    constructor () {
        super();
	    this.getSite = this.getSite.bind(this);
	    //this.checkSelected = this.checkSelected.bind(this);
	    //this.selectAfter = this.selectAfter.bind(this);
	    //this.closeAfter = this.closeAfter.bind(this);
	    //this.loadingAfter = this.loadingAfter.bind(this);
    }

    state = {
	    site: Store.getData('site'),
	    select: Store.getData('select'),
	    loading: Store.getData('loading')
    }

	componentWillMount () {
		console.log('react');
		Store.addChangeListener('getSite', this.getSite);
		Actions.getSite();
	}

	componentDidMount () {
		//Store.addChangeListener('checkSelected', this.checkSelected);
		//Actions.checkSelected();
		//setInterval(() => {
		//	Store.addChangeListener('checkSelected', this.checkSelected);
		//	Actions.checkSelected();
		//}, 5000);
	}

	getSite () {
		let site = Store.getData('site');
		let loading = Store.getData('loading');
		this.setState({ site, loading });
	}

	//checkSelected () {
	//	this.setState({
	//		site: Store.getData('site')
	//	});
	//}
	//
	//selectAfter () {
	//	this.setState({
	//		site: Store.getData('site'),
	//		select: Store.getData('select')
	//	}, () => Store.removeChangeListener('selectSite'));
	//}
	//
	//closeAfter () {
	//	this.setState({
	//		site: Store.getData('site'),
	//		select: Store.getData('select')
	//	}, () => Store.removeChangeListener('close'));
	//}
	//
	//submitAfter () {
	//	this.setState({
	//		site: Store.getData('site'),
	//		select: Store.getData('select'),
	//		loading: Store.getData('loading')
	//	}, () => Store.removeChangeListener('submit'));
	//}
	//
	//loadingAfter () {
	//	this.setState({ loading: Store.getData('loading') }, () => Store.removeChangeListener('loading'));
	//}

	//selectSite (el, index) {
	//	if (el.selected === 1) {
	//		return false;
	//	}
	//	Store.addChangeListener('selectSite', this.selectAfter);
	//	Actions.selectSite(el, index);
	//}
	//
	//close (index, siteIndex) {
	//	Store.addChangeListener('close', this.closeAfter);
	//	Actions.close(index, siteIndex);
	//}
	//
	//submit () {
	//	Store.addChangeListener('loading', this.loading);
	//	Actions.loading();
	//	Store.addChangeListener('submit', this.submitAfter);
	//	Actions.submit();
	//}

	render () {
		return (
			<div>
				<Title />
				<Site selectSite={this.selectSite} site={this.state.site} />
				<Bottom submit={this.submit} close={this.close} select={this.state.select} />
				<Loading display={this.state.loading} />
			</div>
		);
	}
}

export default Controller;
